# Generated by Django 4.1.2 on 2022-10-17 01:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Debito", "Debito"),
                            ("Boleto", "Boleto"),
                            ("Financiamento", "Financiamento"),
                            ("Credito", "Credito"),
                            ("Recebimento Emprestimo", "Emprestimo"),
                            ("Vendas", "Vendas"),
                            ("Recebimento TED", "Ted"),
                            ("Recebimento DOC", "Doc"),
                            ("Aluguel", "Aluguel"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=30)),
                ("cpf", models.CharField(max_length=11)),
                ("card", models.CharField(max_length=30)),
                ("time", models.TimeField()),
                ("store_owner", models.CharField(max_length=14)),
                ("store_name", models.CharField(max_length=19)),
            ],
        ),
    ]
