# Generated by Django 4.1.2 on 2022-10-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Débito", "Debito"),
                            ("Boleto", "Boleto"),
                            ("Financiamento", "Financiamento"),
                            ("Crédito", "Credito"),
                            ("Recebimento Empréstimo", "Emprestimo"),
                            ("Vendas", "Vendas"),
                            ("Recebimento TED", "Ted"),
                            ("Recebimento DOC", "Doc"),
                            ("Aluguel", "Aluguel"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateField()),
                ("value", models.IntegerField()),
                ("cpf", models.CharField(max_length=11)),
                ("card", models.IntegerField()),
                ("time", models.DateTimeField()),
                ("store_owner", models.CharField(max_length=14)),
                ("store_name", models.CharField(max_length=19)),
            ],
        ),
    ]
